== Goals

=== Develop an <<#applicant_tracking_system, Applicant tracking system>> server application.

==== Requirements

* The application:

. *MUST* only permit authenticated access.

. *MUST* only permit secure access.

. *MUST* maintain a collection of  <<professional_profile, professional profiles>>.
+
For the collection, the application:

.. *MUST* provide users with the ability, when permitted, to add items.

.. *MUST* provide users with the ability, when permitted, to remove items.

.. *MUST* provide users with the ability, when permitted, to modify items.

.. *MUST* provide users with the ability, when permitted, to retrieve items.

.. *MUST* provide users with the ability, when permitted, to classify items as _activated_.
+
Activated items:

... *MUST* not be considered deactivated.

.. *MUST* provide users with the ability, when permitted, to classify items as _deactivated_.
+
Deactivated items:

... *MUST* not be considered activated.

. *MUST* provide users with the ability, when permitted, to specify <<qualification, qualifications>>.
+
When a user provides a specification, the application:

.. *MUST* return a collection of <<professional_profile, professional profiles>>.
+
Items within the returned collection:

... *MUST* come from the collection of <<professional_profile, professional profiles>> maintained by the application.

... *MUST* be classified as _activated_.

... *MUST* be graded.
+
The grade:

.... *SHOULD* be based on, and only on, how well its <<qualification, qualifications>> match the user's specification.

... *MUST* exceed the grade threshold if one is specified by the user.

=== Implement an <<#applicant_tracking_system, Applicant Tracking System>> web client.

==== Requirements

* The application:

. *SHOULD* be graphical in nature.

. *MUST* be accessible from a modern browser.

. *MUST* provide users with the ability authenticate.

. *MUST* provide users with the ability the specify <<qualification, qualifications>>, when permitted by the server.
+
The user's specification:

.. *MUST* be used to search the server for <<candidate, candidates>>.
+
The search results:

... *MUST* be displayed.

... *MAY* be abstracts of complete records.
+
In this case, the application:

.... *MUST* provide users with the ability to view complete records.
